FROM --platform=linux/arm64 flink:2.0.0-scala_2.12-java11

USER root

RUN apt-get update && apt-get install -y \
    python3 \
    python3-venv \
    python3-dev \
    build-essential \
    openjdk-11-jdk \
    wget \
 && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-arm64
ENV PATH=$JAVA_HOME/bin:$PATH

RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

RUN pip install --upgrade pip setuptools wheel
RUN pip install apache-flink==2.0.0

COPY requirements.txt .
RUN pip install -r requirements.txt

# Add Avro + Confluent registry JARs
RUN curl -L https://repo1.maven.org/maven2/org/apache/flink/flink-avro/${FLINK_VERSION}/flink-avro-${FLINK_VERSION}.jar \
    -o /opt/flink/lib/flink-avro-${FLINK_VERSION}.jar

RUN curl -L https://repo1.maven.org/maven2/org/apache/flink/flink-sql-avro-confluent-registry/${FLINK_VERSION}/flink-sql-avro-confluent-registry-${FLINK_VERSION}.jar \
        -o /opt/flink/lib/flink-sql-avro-confluent-registry-${FLINK_VERSION}.jar

RUN chmod -R 777 /opt/flink/lib/*.jar

USER flink