# Start from a native ARM64 image
FROM --platform=linux/arm64 eclipse-temurin:21-jre-jammy

ENV FLINK_VERSION=2.0.0
ENV SCALA_VERSION=2.12

# Install dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    python3 \
    python3-pip \
    python3-dev \
    build-essential \
    && ln -s /usr/bin/python3 /usr/bin/python \
    && rm -rf /var/lib/apt/lists/*

# Download and Install Flink
RUN curl -L https://archive.apache.org/dist/flink/flink-${FLINK_VERSION}/flink-${FLINK_VERSION}-bin-scala_${SCALA_VERSION}.tgz | tar -xzC /opt \
    && mv /opt/flink-${FLINK_VERSION} /opt/flink

WORKDIR /opt/flink
ENV PATH=$PATH:/opt/flink/bin

ENTRYPOINT ["/opt/flink/bin/flink-console.sh"]

# Flink ports
EXPOSE 8081 6123

# Default entrypoint for Flink images
#ENTRYPOINT ["/opt/flink/bin/kubernetes-jobmanager.sh"]

